### ISSUE TITLE
thread 'when::tests::on_vec' panicked at 'leaks detected', crates/verona-rt/src/scheduler.rs:54:17

### ISSUE THREAD

**Issue by aDotInTheVoid** [aDotInTheVoid/boxcars#16]
On d5639994f6dd6af210d366a7ed6ca2ff841f2b72

```
while cargo t --lib -p verona-rt ; do :; done
```

will eventually fail with:

```
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests src/lib.rs (target/debug/deps/verona_rt-d9aca5cc7dcb1261)

running 17 tests
test cown::tests::actualcown_constats_right ... ok
test scheduler::tests::panic_safe ... ignored, https://github.com/aDotInTheVoid/boxcars/issues/4
test cown::tests::clone_minimal ... ok
test when::tests::double_aquire - should panic ... ok
test cown::tests::dtor ... FAILED
test cown::tests::dtor_clone ... ok
test cown::tests::leak_detector_new ... ok
test cown::tests::new ... ok
test cown::tests::new_minimal ... ok
test cown::tests::read_modify_write ... ok
test cown::tests::write_stress ... ok
test scheduler::tests::basic_run ... ok
test when::tests::basic ... ok
test when::tests::when_two ... ok
test when::tests::on_vec ... ok
test scheduler::tests::run_from_multi_threads ... ok
test cown::tests::clone_notnull ... ok

failures:

---- cown::tests::dtor stdout ----
thread 'cown::tests::dtor' panicked at 'leaks detected', crates/verona-rt/src/scheduler.rs:54:17


failures:
    cown::tests::dtor

test result: FAILED. 15 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.61s

error: test failed, to rerun pass `-p verona-rt --lib`
```

**Comment by aDotInTheVoid** [comment]
Reduced:  

```
while cargo t --  when::tests::double_aquire  scheduler::tests::run_from_multi_threads; do :; done
```

```
running 2 tests
test when::tests::double_aquire - should panic ... ok
test scheduler::tests::run_from_multi_threads ... FAILED

failures:

---- scheduler::tests::run_from_multi_threads stdout ----
thread '<unnamed>' panicked at 'leaks detected', crates/verona-rt/src/scheduler.rs:54:17
thread 'scheduler::tests::run_from_multi_threads' panicked at 'a scoped thread panicked', crates/verona-rt/src/scheduler.rs:80:9


failures:
    scheduler::tests::run_from_multi_threads

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 5 filtered out; finished in 0.51s

error: test failed, to rerun pass `-p verona-rt --lib`
```

**Comment by aDotInTheVoid** [comment]
Standalone:

```rust
use verona_rt::{
    cown::CownPtr,
    scheduler::{self, with_leak_detector},
    when::when2,
};

fn double_aquire() {
    scheduler::with_leak_detector(|| {
        let c1 = CownPtr::new(10);
        let c2 = c1.clone();
        when2(&c1, &c2, |_, _| loop {});
    });
}

fn generate_work() {
    std::thread::scope(|s| {
        for _ in 0..10 {
            s.spawn(|| {
                for _ in 0..100 {
                    with_leak_detector(|| {});
                }
            });
        }
    });
}

#[test]
fn main() {
    for _ in 0..20 {
        let a = std::thread::spawn(generate_work);
        let b = std::thread::spawn(double_aquire);

        a.join().unwrap();
        b.join().unwrap_err();
    }
}
```

Or even further:

```rust
use verona_rt::scheduler::with;

fn double_aquire() {
    with(|| {
        panic!("give up");
    });
}

fn generate_work() {
    std::thread::scope(|s| {
        for _ in 0..10 {
            s.spawn(|| {
                for _ in 0..100 {
                    with(|| {});
                }
            });
        }
    });
}

#[test]
fn main() {
    for _ in 0..20 {
        let a = std::thread::spawn(generate_work);
        let b = std::thread::spawn(double_aquire);

        a.join().unwrap();
        b.join().unwrap_err();
    }
}
```

**Comment by aDotInTheVoid** [comment]
It's not about the thread exiting while panicing:

```rust
use verona_rt::scheduler::with_leak_detector;

fn generate_work() {
    std::thread::scope(|s| {
        for _ in 0..10 {
            s.spawn(|| {
                for _ in 0..100 {
                    with_leak_detector(|| {});
                }
            });
        }
    });
}

fn panic_with_sched() {
    let msg = std::panic::catch_unwind(|| with_leak_detector(|| panic!("welp")))
        .unwrap_err()
        .downcast::<&str>()
        .unwrap();
    assert_eq!(&**msg, "welp");
}

#[test]
fn main() {
    for _ in 0..20 {
        let a = std::thread::spawn(generate_work);
        let b = std::thread::spawn(panic_with_sched);

        a.join().unwrap();
        b.join().unwrap()
    }
}
```

**Comment by aDotInTheVoid** [comment]
Likely #21
